import subprocess
import time
from pathlib import Path
from datetime import datetime
import hashlib

VAULT_DIR = Path.home() / "ForestVault"
RND_DIR = VAULT_DIR / "rd_seed"
RND_DIR.mkdir(exist_ok=True)

def log_chain(event_type, details=""):
    timestamp = datetime.now().isoformat()
    entry = f"{timestamp} | {event_type} | {details}"
    h = hashlib.sha256(entry.encode()).hexdigest()
    with open(VAULT_DIR / "training_chain.json", "a") as f:
        f.write(f"{entry} | Hash: {h}\n")

print("=== Forest Heavy R&D Box Online (Parallel What-If Engine) ===")
print("This organ runs independent blue-team research and saves ideas to rd_seed/")

while True:
    try:
        prompt = """You are Forest Heavy R&D. Run a 10th-man / Steel-manning session.
Current focus: blue-team defense against evolving phishing, supply-chain, and social engineering attacks.
Generate 3 bold but safe, ethical, shippable training ideas or tool improvements.
Output ONLY markdown with clear titles and actionable steps. No fluff."""
        
        result = subprocess.run(["ollama", "run", "qwen2:0.5b", prompt], capture_output=True, text=True, timeout=90)
        output = result.stdout.strip()
        
        if output:
            idea_file = RND_DIR / f"rd_idea_{int(time.time())}.md"
            with open(idea_file, "w") as f:
                f.write(f"# Forest R&D Idea - {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n{output}\n\n---\nGenerated by Heavy R&D Box\n")
            print(f"[R&D Box] New idea saved → {idea_file.name}")
            log_chain("RND_IDEA", idea_file.name)
        
        time.sleep(300)  # every 5 minutes - heavy but not burning the mini
    except Exception as e:
        print(f"[R&D Box] Error: {e}")
        time.sleep(60)
