import subprocess
from pathlib import Path
import time
from datetime import datetime
import hashlib

VAULT_DIR = Path.home() / "ForestVault"
FORGE_SANDBOX = VAULT_DIR / "forge_sandbox"
FORGE_SANDBOX.mkdir(exist_ok=True)

def log_to_cryptex(event_type, details=""):
    timestamp = datetime.now().isoformat()
    entry = f"{timestamp} | {event_type} | {details}"
    h = hashlib.sha256(entry.encode()).hexdigest()[:16]
    with open(VAULT_DIR / "training_chain.json", "a") as f:
        f.write(f"{entry} | Hash: {h}\n")
    print(f"[CRYPTEX] {event_type} logged | Hash: {h}")

print("=== Forest Forge - Tight Steel-Manned Mode ===")
print("Only clean, concrete, self-tested proposals will be generated.\n")

while True:
    try:
        print(f"\n[Forge] Running tight scan @ {datetime.now().strftime('%H:%M:%S')}")

        prompt = """You are Forest Forge. Analyze the current Forest codebase.
Existing organs: supervisor, brain, repl, mouth, scout, warden, forge, agents, vault.

Rules - Follow exactly:
- Output ONLY clean proposals. No thinking steps visible.
- For each proposal use this exact format:

PROPOSAL: [Short Name] - [One sentence what it does]

Steel-Manned Description:
[Strongest possible version of the idea, written clearly]

Rigorous Self-Test:
- Edge cases considered:
- Potential flaws and risks:
- How it was mentally tested:

Concrete Changes:
- File(s) to change:
- Small, safe diff or code snippet:

- Keep every suggestion small, safe, and ethical.
- Never suggest large rewrites or new organs.
- Be brutally honest about risks.

Generate 2-4 high-quality proposals only."""

        result = subprocess.run(["ollama", "run", "qwen3:8b", prompt], capture_output=True, text=True, timeout=90)
        output = result.stdout.strip()

        if output:
            idea_file = FORGE_SANDBOX / f"forge_proposal_{int(time.time())}.md"
            with open(idea_file, "w") as f:
                f.write(f"# Forge Proposal - {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n")
                f.write(output)
                f.write("\n\n---\nGenerated by Forge. Review and approve in REPL or Warden before any changes.")
            print(f"[Forge] New tight proposal saved: {idea_file.name}")
            log_to_cryptex("FORGE_PROPOSAL", idea_file.name)
        else:
            print("[Forge] No usable output this cycle.")

        time.sleep(300)  # 5 min cycle

    except KeyboardInterrupt:
        print("\nForge shutting down.")
        break
    except Exception as e:
        print(f"[Forge] Error: {e}")
        time.sleep(60)
