import subprocess
from pathlib import Path
import time
from datetime import datetime
import hashlib
import tempfile
import shutil
import os

VAULT_DIR = Path.home() / "ForestVault"
FORGE_SANDBOX = VAULT_DIR / "forge_sandbox"
DANGER_DIR = VAULT_DIR / "danger_room"
DANGER_DIR.mkdir(exist_ok=True)

VENV_PYTHON = Path("venv/bin/python").resolve()

def log_to_cryptex(event_type, details=""):
    timestamp = datetime.now().isoformat()
    entry = f"{timestamp} | {event_type} | {details}"
    h = hashlib.sha256(entry.encode()).hexdigest()[:16]
    with open(VAULT_DIR / "training_chain.json", "a") as f:
        f.write(f"{entry} | Hash: {h}\n")
    print(f"[CRYPTEX] {event_type} logged | Hash: {h}")

def danger_room():
    print("\n=== Warden Danger Room - Configurable Isolated Simulation ===")
    target = input("Target to fork: ").strip()
    if not target:
        return

    target_path = Path(target)
    if not target_path.exists():
        print(f"Target {target} not found.")
        return

    max_minutes = int(input("Max runtime in minutes (1-60): ").strip() or "10")
    max_minutes = max(1, min(60, max_minutes))
    print(f"Simulation will run up to {max_minutes} minutes or until killed.")

    try:
        with tempfile.TemporaryDirectory(dir=DANGER_DIR) as temp_dir:
            temp_path = Path(temp_dir)
            shutil.copy(target_path, temp_path / target_path.name)

            cmd = [str(VENV_PYTHON), str(temp_path / target_path.name)]

            print("Simulation started. Type 'kill' to stop early.")

            proc = subprocess.Popen(
                cmd,
                cwd=temp_path,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                env={"DISPLAY": "", "HEADLESS": "1"}
            )

            timeout = max_minutes * 60
            start_time = time.time()

            while proc.poll() is None:
                if time.time() - start_time > timeout:
                    print("Simulation reached max time limit.")
                    proc.kill()
                    break
                try:
                    user_cmd = input("Sim> ").strip().lower()
                    if user_cmd == "kill":
                        print("Killing simulation...")
                        proc.kill()
                        break
                except KeyboardInterrupt:
                    proc.kill()
                    break

            output, _ = proc.communicate(timeout=10)
            print("\nSimulation Output:")
            print(output[:2000] + "..." if len(output) > 2000 else output)

            log_to_cryptex("DANGER_SIMULATION", f"Target: {target} - Completed or killed safely")

            suggestion = f"PROPOSAL: DangerRoomInsight_{target_path.stem} - Simulation results from {target} suggest improvements in robustness or safety."
            proposal_file = FORGE_SANDBOX / f"danger_insight_{int(time.time())}.md"
            with open(proposal_file, "w") as f:
                f.write(f"# Danger Room Insight - {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n")
                f.write(suggestion + "\n\n")
                f.write("Simulation output summary:\n" + output[:1000] + "...\n")
                f.write("\n---\nGenerated by Warden Danger Room. Review and approve in REPL or Warden.")
            print(f"Proposal written to Forge sandbox: {proposal_file.name}")

    except Exception as e:
        print(f"Simulation error: {e}")
        log_to_cryptex("DANGER_SIMULATION_FAILED", f"Target: {target} - {e}")

def main():
    print("=== Warden - Quarantine and Danger Room Guardian ===")
    print("Commands: list, danger, exit\n")

    while True:
        cmd = input("Warden> ").strip().lower()
        if cmd in ["exit", "quit"]:
            print("Warden shutting down.")
            break
        elif cmd == "danger":
            danger_room()
        elif cmd == "list":
            print("Danger Room ready. Use 'danger' to run isolated simulations.")
        else:
            print("Available: danger, list, exit")

if __name__ == "__main__":
    main()
